version: '2.4'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - ~/docker-volumes/mysql-social:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 2s
  app:
    container_name: social
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASS: pass
      TEMPLATES: /templates
      MIGRATION_DIR: /migrations
    depends_on:
      db:
        condition: service_healthy
